name: 🚀 Request a Feature
description: I have a suggestion.
labels:
  - type/feature
body:
  - type: checkboxes
    attributes:
      label: Confirm there isn't an existing issue for this
      description: Please search to see if an issue already exists for this feature request
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: request
    attributes:
      label: Request
      description: Describe your request, using as much detail as you can. Don't be afraid to any planning you've already done, and take advantage of formatting and lists to make it easier to read!
    validations:
      required: true
  - type: textarea
    id: approaches
    attributes:
      label: Potential approaches
      description: If you have any thoughts on how this could be implemented, provide a quick summary here.
    validations:
      required: false
